"use client";

import React from "react";
import { Archive, ArrowLeft, ChevronDown, ExternalLink, Eye, Globe2, Maximize2, MessageSquare, Plus, Trash2, X } from "lucide-react";
import Button from "./Button";
import Modal from "./Modal";

const STEPS = [
  { label: "Open", detail: "3 steps" },
  { label: "Verify", detail: "2 steps" },
  { label: "Discover", detail: "3 steps" },
  { label: "Act", detail: "5 Paths" },
  { label: "Close", detail: "1 step" },
];

// "03 · Workflow editor — Open stage (default)" — hint is null on the first
// card (no hint written yet → "+ Add Hint" chip); the third card is a step
// whose title hasn't been written ("Step title will come here…"), shown
// as-is rather than invented.
const OPEN_CARDS = [
  { title: "Greet the customer and identify yourself and Orange.", type: "💬 Script", hint: null },
  { title: "Listen to the customer’s opening statement and confirm the primary reason for their contact.", type: "Action", hint: 2 },
  { title: "Step title will come here…", type: "💬 Script", hint: 2 },
];

// "05 · Workflow editor — Act stage (triage paths)" — the Act stage branches
// into named paths (only 4 of the source frame's 5 are legible/in-frame;
// the pill count below reflects what's actually rendered rather than the
// uninspectable 5th). Each path card selects which path's steps show below.
// Step content is only known for the first (selected-by-default) path — the
// other three fall back to an honest empty state instead of invented steps.
const ACT_PATHS = [
  { id: "no-signal", category: "Service", title: "Router light shows no broadband signal", meta: "4 Steps  • 2 trigger cues" },
  { id: "all-devices", category: "Service", title: "WiFi drops on all devices", meta: "5 Steps  • 3 trigger cues" },
  { id: "single-device", category: "Service", title: "Single device cannot stay connected", meta: "3 Steps  • 2 trigger cues" },
  { id: "escalation", category: "Service", title: "Customer needs engineer escalation", meta: "4 Steps  • 1 trigger cue" },
];

const ACT_STEPS_BY_PATH = {
  "no-signal": [
    { title: "Ask the customer which router lights are on and whether broadband is flashing or solid.", type: "Action", hint: 2 },
    { title: "Confirm whether every device loses WiFi or only one device is affected.", type: "Action", hint: 3 },
    { title: "Guide the customer to restart the router only after recording the current light status.", type: "Confirm", hint: 1 },
    { title: "Run the line test and tell the customer whether the issue is local WiFi or broadband service.", type: "Confirm", hint: 2 },
    { title: "If service is down, set expectations for engineer follow-up and confirm the best contact number.", type: "Action", hint: 1 },
  ],
};

const NUMERAL_GLYPHS = ["looks_one", "looks_two", "looks_3", "looks_4", "looks_5"];

// hintsStep / onOpenHints / onCloseHints are lifted to the host (see
// app/[[...slug]]/page.jsx) so the Hints panel ("05a.1"/"05a.2") can be
// passed to <PageLayout rightPanel> and dock as a real column beside this
// page, same as WorkflowFilterPanel/InteractionFilterPanel — not rendered
// as a floating overlay in here.
export default function WorkflowPostPublishPage({ onBack, hintsStep, onOpenHints }) {
  const [pending, setPending] = React.useState(true);
  const [roleplays, setRoleplays] = React.useState(0);
  const [feedback, setFeedback] = React.useState("");
  const [roleplayPanelOpen, setRoleplayPanelOpen] = React.useState(false);
  const [archiveModalOpen, setArchiveModalOpen] = React.useState(false);
  const [activeStage, setActiveStage] = React.useState(0);
  const [selectedPathId, setSelectedPathId] = React.useState(ACT_PATHS[0].id);
  const pathsScrollRef = React.useRef(null);

  const isOpenStage = activeStage === 0;
  const isActStage = activeStage === 3;
  const actSteps = ACT_STEPS_BY_PATH[selectedPathId] || null;

  const discard = () => {
    setPending(false);
    setRoleplays(2);
    setFeedback("Changes discarded. The published workflow is unchanged.");
  };

  const republish = () => {
    setPending(false);
    setRoleplays(0);
    setFeedback("Workflow republished without attached roleplays.");
  };

  return (
    <div style={styles.wrap}>
      <header style={styles.header}>
        <Button variant="icon" size="sm" onClick={onBack} aria-label="Back to workflows"><ArrowLeft size={18} /></Button>
        <span style={styles.workflowIcon}><span className="material-symbols-outlined" style={{ fontSize: 16 }}>podcasts</span></span>
        <div style={styles.headerCopy}>
          <strong style={styles.title}>Home WiFi dropping out — connectivity triage</strong>
          <div style={styles.meta}><span style={styles.activePill}>Active</span><span style={styles.localePill}>en-US</span><span>Generated · Jun 25, 4:22 PM</span><span>Generated by · Ana</span></div>
        </div>
        <Button variant="text" uppercase={false} leadingIcon={<Globe2 size={18} />} style={styles.languageButton}>En</Button>
        <Button variant="icon" size="sm" aria-label="Open workflow view"><Maximize2 size={18} /></Button>
        <Button variant="icon" size="sm" onClick={() => setArchiveModalOpen(true)} aria-label="Archive this workflow"><Archive size={18} /></Button>
      </header>

      <div style={styles.sourceBar}>
        <div style={styles.sourceLeft}>
          <span>Generated from interaction <strong>XYZ1236A</strong></span>
          <Button variant="text" uppercase={false} trailingIcon={<ExternalLink size={13} />} style={styles.sourceAction}>View interaction</Button>
        </div>
        <div style={styles.sourceTags}>
          <span style={styles.sourceTag}>Service request</span>
          <span style={styles.sourceTag}>FCR achieved</span>
          <Button variant="icon" size="sm" aria-label="More interaction details"><ChevronDown size={16} /></Button>
        </div>
      </div>

      {pending && (
        <section style={styles.warning} aria-live="polite">
          <div>
            <strong style={styles.warningTitle}>Changes not published</strong>
            <p style={styles.warningText}>This workflow no longer has any roleplays. Agents will continue to see the published version until you republish.</p>
          </div>
          <div style={styles.warningActions}>
            <Button variant="text" uppercase={false} onClick={discard}>Discard</Button>
            <Button variant="primary" size="sm" uppercase={false} onClick={republish}>Republish</Button>
          </div>
        </section>
      )}

      {feedback && <div style={styles.feedback} role="status">{feedback}</div>}

      <section style={styles.editor}>
        <div style={styles.stepper}>
          {STEPS.map((step, index) => (
            <React.Fragment key={step.label}>
              {index > 0 && <span style={styles.connector} />}
              <Button
                variant="text"
                uppercase={false}
                onClick={() => setActiveStage(index)}
                aria-pressed={index === activeStage}
                style={styles.step}
              >
                <span style={{ ...styles.stepNumber, ...(index === activeStage ? styles.stepNumberActive : {}) }}>{index + 1}</span>
                <span><strong style={{ ...styles.stepLabel, ...(index === activeStage ? styles.stepLabelActive : {}) }}>{step.label}</strong><small style={styles.stepDetail}>{step.detail}</small></span>
              </Button>
            </React.Fragment>
          ))}
          <span style={styles.roleplayDivider} />
          <Button variant="text" uppercase={false} style={styles.roleplayCount} onClick={() => setRoleplayPanelOpen(true)} aria-label={`Open ${roleplays} attached roleplays`}>
            <span style={styles.roleplayCountInner}><small>{roleplays}</small><span>Roleplays</span></span>
          </Button>
        </div>

        {isActStage && (
          <div style={styles.pathsSection}>
            <div style={styles.pathsHeader}>
              <span style={styles.pathsLabel}>Paths</span>
              <span style={styles.pathsCountPill}>{ACT_PATHS.length}</span>
            </div>
            <div style={styles.pathsRow} ref={pathsScrollRef}>
              {ACT_PATHS.map((path) => (
                <Button
                  key={path.id}
                  variant="text"
                  uppercase={false}
                  onClick={() => setSelectedPathId(path.id)}
                  aria-pressed={path.id === selectedPathId}
                  style={{ ...styles.pathCard, ...(path.id === selectedPathId ? styles.pathCardActive : {}) }}
                >
                  <span style={styles.pathCardContent}>
                    <span style={styles.typeChip}>{path.category}</span>
                    <span style={styles.pathTitle}>{path.title}</span>
                    <span style={styles.pathMeta}>{path.meta}</span>
                  </span>
                </Button>
              ))}
            </div>
          </div>
        )}

        <div style={styles.cards}>
          {isOpenStage && OPEN_CARDS.map((card, index) => (
            <StepCard
              key={card.title}
              index={index}
              title={card.title}
              type={card.type}
              hint={card.hint}
              selected={hintsStep?.title === card.title}
              onOpenHints={() => onOpenHints?.({ title: card.title, hint: card.hint })}
            />
          ))}
          {isActStage && (
            actSteps ? (
              <>
                <span style={styles.stepsLabel}>Steps</span>
                {actSteps.map((card, index) => (
                  <StepCard
                    key={card.title}
                    index={index}
                    title={card.title}
                    type={card.type}
                    hint={card.hint}
                    selected={hintsStep?.title === card.title}
                    onOpenHints={() => onOpenHints?.({ title: card.title, hint: card.hint })}
                  />
                ))}
              </>
            ) : (
              <div style={styles.emptyStage}>No steps configured for this path yet.</div>
            )
          )}
          {!isOpenStage && !isActStage && (
            <div style={styles.emptyStage}>No steps configured for this stage yet.</div>
          )}
        </div>

        <Button variant="text" uppercase={false} leadingIcon={<Plus size={16} />} style={styles.addStep}>Add a step</Button>
      </section>
      {roleplayPanelOpen && (
        <RoleplayPanel
          initialCount={roleplays}
          onCountChange={setRoleplays}
          onClose={() => setRoleplayPanelOpen(false)}
        />
      )}
      <Modal
        open={archiveModalOpen}
        onDismiss={() => setArchiveModalOpen(false)}
        title="Archive this workflow?"
        body="Archiving moves this workflow to Archived. The source interaction remains linked."
        confirmLabel="Archive"
        confirmTone="danger"
        onConfirm={() => { setArchiveModalOpen(false); onBack(); }}
      />
    </div>
  );
}

function StepCard({ index, title, type, hint, selected, onOpenHints }) {
  return (
    <article style={{ ...styles.card, ...(selected ? styles.cardSelected : {}) }}>
      <span style={styles.cardNumber}><span className="material-symbols-outlined" style={{ fontSize: 16 }}>{NUMERAL_GLYPHS[index] || "looks_one"}</span></span>
      <div style={styles.cardCopy}><strong>{title}</strong><span style={styles.typeChip}>{type}</span></div>
      {hint ? (
        <Button variant="text" leadingIcon={<MessageSquare size={14} />} onClick={onOpenHints} style={styles.hintChip}>
          Hint <b style={styles.hintCount}>{hint}</b>
        </Button>
      ) : (
        <Button variant="text" leadingIcon={<Plus size={14} />} onClick={onOpenHints} style={styles.hintChip}>Add Hint</Button>
      )}
      <Button variant="icon" size="sm" aria-label={`Remove step ${index + 1}`}><Trash2 size={15} /></Button>
    </article>
  );
}

const PANEL_ROLEPLAYS = [
  { id: "slow-speed", title: "Slow speed after router restart", category: "Connectivity", modified: "Jun 18, 2026" },
  { id: "dropout", title: "Intermittent dropout - home office", category: "WiFi support", modified: "Jun 21, 2026", calibration: true },
  { id: "amber-light", title: "Router light flashing amber", category: "Broadband", modified: "Jun 22, 2026" },
  { id: "new-device", title: "Unable to connect a new device", category: "Device setup", modified: "Jun 24, 2026" },
];

function RoleplayPanel({ initialCount, onCountChange, onClose }) {
  const [query, setQuery] = React.useState("");
  const [status, setStatus] = React.useState("all");
  const [viewSelected, setViewSelected] = React.useState(false);
  const [selected, setSelected] = React.useState(() => new Set(PANEL_ROLEPLAYS.slice(0, initialCount).map((item) => item.id)));

  const visible = PANEL_ROLEPLAYS.filter((item) => {
    const matchesQuery = `${item.title} ${item.category}`.toLowerCase().includes(query.trim().toLowerCase());
    const matchesStatus = status === "all" || (status === "calibration" ? item.calibration : !item.calibration);
    return matchesQuery && matchesStatus && (!viewSelected || selected.has(item.id));
  });

  const toggle = (id) => {
    const next = new Set(selected);
    if (next.has(id)) next.delete(id); else next.add(id);
    setSelected(next);
    onCountChange(next.size);
  };

  return (
    <aside style={styles.roleplayPanel} aria-label="Roleplays panel">
      <header style={styles.panelHeader}>
        <strong>Roleplays</strong>
        <Button variant="icon" size="sm" onClick={onClose} aria-label="Close roleplays panel"><X size={20} /></Button>
      </header>
      <div style={styles.panelTools}>
        <input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search roleplays" aria-label="Search roleplays" style={styles.panelSearch} />
        <select value={status} onChange={(event) => setStatus(event.target.value)} aria-label="Filter roleplay status" style={styles.panelSelect}>
          <option value="all">All statuses</option>
          <option value="ready">Ready</option>
          <option value="calibration">In calibration</option>
        </select>
      </div>
      <div style={styles.panelSummary}>
        <strong>{selected.size} roleplays selected</strong>
        <div style={styles.panelSummaryActions}>
          <Button variant="text" uppercase={false} leadingIcon={<Eye size={16} />} style={styles.panelLink} onClick={() => setViewSelected((value) => !value)}>{viewSelected ? "View all" : "View selected"}</Button>
          <Button variant="text" uppercase={false} style={styles.panelLink} onClick={() => { setSelected(new Set()); onCountChange(0); }}>Clear all</Button>
        </div>
      </div>
      <div style={styles.panelList}>
        {visible.map((item) => {
          const attached = selected.has(item.id);
          return (
            <article key={item.id} style={styles.panelCard}>
              <div style={styles.panelCardCopy}>
                <strong>{item.title}</strong>
                <div style={styles.panelMeta}><span style={styles.typeChip}>{item.category}</span>{item.calibration && <span style={styles.calibrationChip}>In calibration</span>}<span>Last modified on {item.modified}</span></div>
              </div>
              <Button variant="icon" size="sm" onClick={() => toggle(item.id)} aria-label={`${attached ? "Remove" : "Add"} ${item.title}`} style={styles.panelCardAction}>
                {attached ? <Trash2 size={16} /> : <Plus size={17} />}
              </Button>
            </article>
          );
        })}
        {!visible.length && <div style={styles.panelEmpty}>No roleplays match your search.</div>}
      </div>
      <footer style={styles.panelFooter}>
        <Button variant="text" uppercase={false} leadingIcon={<Plus size={16} />} style={styles.panelAdd}>Add roleplay</Button>
        <Button variant="text" uppercase={false} onClick={onClose} style={styles.panelDone}>Done</Button>
      </footer>
    </aside>
  );
}

const styles = {
  wrap: { display: "flex", flexDirection: "column", gap: 16, width: "100%", minHeight: 0 },
  header: { height: 64, flexShrink: 0, padding: "8px 12px", border: "2px solid white", borderRadius: 12, background: "#FCFBFF", display: "flex", alignItems: "center", gap: 8, boxSizing: "border-box" },
  workflowIcon: { width: 32, height: 32, borderRadius: 999, background: "var(--color-icon-tertiary-bg)", color: "var(--color-icon-tertiary-fg)", display: "grid", placeItems: "center" },
  headerCopy: { flex: 1, display: "flex", flexDirection: "column", gap: 4 },
  title: { fontSize: 16, fontWeight: 500, color: "var(--color-text-medium)" },
  meta: { display: "flex", alignItems: "center", gap: 8, fontSize: 12, color: "var(--color-text-tertiary)" },
  activePill: { padding: "4px 6px", borderRadius: 4, background: "var(--tile-green-deep-bg)", color: "var(--color-success-deep)", fontSize: 11 },
  localePill: { padding: "4px 10px", borderRadius: 999, background: "var(--color-border-card-soft)", color: "var(--color-text-medium)" },
  languageButton: { height: 32, paddingInline: 12, border: "1px solid #EFEFFF", borderRadius: 8, color: "var(--grey-700)", fontWeight: 700 },
  sourceBar: { height: 40, flexShrink: 0, padding: "4px 8px 4px 16px", borderRadius: 12, background: "var(--chart-blue-100)", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 12, color: "var(--grey-700)", boxSizing: "border-box" },
  sourceLeft: { display: "flex", alignItems: "center", gap: 12 },
  sourceAction: { color: "var(--do-brand-blue)", fontWeight: 600 },
  sourceTags: { display: "flex", alignItems: "center", gap: 4 },
  sourceTag: { height: 24, padding: "3px 8px", borderRadius: 4, background: "#F9F9FF", color: "#424659", fontSize: 12, lineHeight: "18px", boxSizing: "border-box" },
  warning: { height: 64, flexShrink: 0, padding: 16, border: "1px solid white", borderRadius: 8, background: "#FFFDFA", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, boxSizing: "border-box" },
  warningTitle: { display: "block", marginBottom: 4, fontSize: 14, lineHeight: "22px", fontWeight: 500, letterSpacing: "0.1px", color: "#6B4B0B" },
  warningText: { margin: 0, fontSize: 14, lineHeight: "20px", letterSpacing: "0.17px", color: "#8C620E", whiteSpace: "nowrap" },
  warningActions: { flexShrink: 0, display: "flex", alignItems: "center", gap: 8 },
  feedback: { padding: "10px 16px", borderRadius: 10, background: "var(--tile-green-deep-bg)", color: "var(--color-success-deep)", fontSize: 12 },
  editor: { flex: 1, minHeight: 420, padding: "16px 16px 24px", borderRadius: 12, background: "var(--surface-white)" },
  stepper: { minHeight: 64, display: "flex", alignItems: "center" },
  step: { height: "auto", padding: 0, display: "flex", alignItems: "center", gap: 8, flexShrink: 0 },
  stepNumber: { width: 40, height: 40, borderRadius: 999, background: "var(--chart-gray-50)", color: "var(--grey-700)", display: "grid", placeItems: "center", fontSize: 14 },
  stepNumberActive: { background: "var(--do-brand-blue)", color: "white" },
  stepLabel: { display: "block", color: "var(--grey-700)", fontSize: 12, fontWeight: 500 },
  stepLabelActive: { color: "var(--do-brand-blue)" },
  stepDetail: { display: "block", marginTop: 2, color: "var(--color-text-tertiary)", fontSize: 10 },
  connector: { width: 28, height: 2, marginInline: 8, background: "var(--color-border-card-soft)" },
  roleplayDivider: { width: 1, height: 40, marginLeft: "auto", marginRight: 16, background: "var(--color-border-card-soft)" },
  roleplayCount: { width: 80, height: 52, padding: 0, color: "var(--grey-700)", fontSize: 12 },
  roleplayCountInner: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 2 },
  cards: { marginTop: 16, display: "flex", flexDirection: "column", gap: 12 },
  card: { minHeight: 72, padding: 16, border: "2px solid var(--color-border-card-soft)", borderRadius: 8, display: "flex", alignItems: "center", gap: 12 },
  cardSelected: { border: "2px solid var(--do-brand-blue)", background: "var(--tile-blue-bg)" },
  cardNumber: { width: 32, height: 32, borderRadius: 8, background: "var(--tile-blue-bg)", color: "var(--tile-blue-fg)", display: "grid", placeItems: "center", flexShrink: 0 },
  cardCopy: { flex: 1, display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 8, fontSize: 14, color: "var(--color-text-medium)" },
  typeChip: { padding: "3px 8px", borderRadius: 4, background: "var(--color-card-emoji-bg)", fontSize: 11, color: "var(--grey-700)" },
  hintChip: { height: 32, padding: "0 10px", borderRadius: 8, background: "var(--color-border-card-soft)", display: "flex", alignItems: "center", gap: 5, fontSize: 12, textTransform: "uppercase", flexShrink: 0, color: "var(--color-text-medium)" },
  hintCount: { minWidth: 20, height: 20, paddingInline: 5, borderRadius: 20, background: "#DDE1FF", display: "inline-grid", placeItems: "center", fontSize: 12, fontWeight: 500 },
  addStep: { marginTop: 12, paddingInline: 10, background: "var(--color-border-card-soft)", borderRadius: 4 },
  stepsLabel: { fontSize: 14, fontWeight: 500, color: "var(--grey-700)" },
  emptyStage: { minHeight: 96, border: "1px dashed var(--color-border-card-soft)", borderRadius: 8, display: "grid", placeItems: "center", color: "var(--color-text-tertiary)", fontSize: 13 },
  pathsSection: { marginTop: 16, display: "flex", flexDirection: "column", gap: 8 },
  pathsHeader: { display: "flex", alignItems: "center", gap: 4 },
  pathsLabel: { fontSize: 14, fontWeight: 500, color: "var(--grey-700)" },
  pathsCountPill: { padding: "4px 6px", borderRadius: 6, background: "#E6FAEB", color: "#009225", fontSize: 12, fontWeight: 700 },
  pathsRow: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 4 },
  pathCard: {
    width: 320, minWidth: 320, height: "auto", padding: 16,
    display: "flex", alignItems: "flex-start", justifyContent: "flex-start",
    border: "2px solid var(--color-border-card-soft)", borderRadius: 8, background: "white", flexShrink: 0,
  },
  pathCardActive: { border: "2px solid var(--do-brand-blue)", background: "var(--tile-blue-bg)" },
  pathCardContent: { display: "flex", flexDirection: "column", alignItems: "flex-start", gap: 8, width: "100%" },
  pathTitle: { fontSize: 16, fontWeight: 500, color: "var(--color-text-medium)", textAlign: "left" },
  pathMeta: { fontSize: 12, color: "#6B7280" },
  roleplayPanel: { position: "fixed", zIndex: 60, top: 16, bottom: 16, right: 24, width: 408, borderRadius: 16, background: "white", boxShadow: "var(--shadow-8)", display: "flex", flexDirection: "column", overflow: "hidden", boxSizing: "border-box" },
  panelHeader: { height: 56, padding: "8px 16px", display: "flex", alignItems: "center", justifyContent: "space-between", fontSize: 16, color: "#1B1B1F", boxSizing: "border-box" },
  panelTools: { height: 48, padding: "8px 16px", display: "flex", gap: 8, boxSizing: "border-box" },
  panelSearch: { width: 248, height: 32, padding: "0 12px", border: "1px solid #D2D5E2", borderRadius: 6, fontFamily: "var(--font-sans)", fontSize: 14, color: "#2C2F42", outline: "none", boxSizing: "border-box" },
  panelSelect: { width: 120, height: 32, padding: "0 8px", border: "1px solid #D2D5E2", borderRadius: 6, background: "#F9FAFB", fontFamily: "var(--font-sans)", fontSize: 13, color: "#45464F" },
  panelSummary: { minHeight: 54, margin: "0 16px 8px", padding: "0 12px", border: "1px solid #90CAFF", borderRadius: 10, background: "#E3F2FD", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8, fontSize: 12, color: "#2C2F42" },
  panelSummaryActions: { display: "flex", alignItems: "center", gap: 10, flexShrink: 0 },
  panelLink: { height: 28, color: "var(--do-brand-blue)", fontSize: 11, fontWeight: 600 },
  panelList: { flex: 1, minHeight: 0, padding: "0 16px 8px", overflowY: "auto", display: "flex", flexDirection: "column", gap: 8 },
  panelCard: { minHeight: 84, padding: 16, border: "1px solid #EFEFFF", borderRadius: 12, display: "flex", alignItems: "flex-start", gap: 4, boxSizing: "border-box" },
  panelCardCopy: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 4, color: "#2C2F42", fontSize: 14 },
  panelMeta: { display: "flex", flexWrap: "wrap", alignItems: "center", gap: 8, color: "#5A5D72", fontSize: 10 },
  calibrationChip: { height: 24, padding: "5px 6px", borderRadius: 4, background: "#FFFBEB", color: "#D97706", boxSizing: "border-box", fontSize: 11 },
  panelCardAction: { background: "#EFEFFF", color: "#2C2F42", flexShrink: 0 },
  panelEmpty: { minHeight: 96, border: "1px dashed #D2D5E2", borderRadius: 12, display: "grid", placeItems: "center", color: "#72768B", fontSize: 13 },
  panelFooter: { height: 56, padding: "8px 24px 16px", display: "flex", alignItems: "center", justifyContent: "flex-end", gap: 16, boxSizing: "border-box" },
  panelAdd: { color: "var(--do-brand-blue)", fontSize: 14, fontWeight: 500 },
  panelDone: { height: 32, paddingInline: 16, border: "1px solid rgba(25,118,210,.5)", borderRadius: 999, color: "var(--do-brand-blue)", fontSize: 14, fontWeight: 500 },
};
