// Data for the "KPI Space" landing direction — the outcome-space surface from
// the [Ask Mira Pro] Landing page ticket (Jun 19 sharpening): pre-populated
// outcome KPIs, AMP-authored stories (generated by tasks, default-public),
// and the space's chats. Figures are illustrative for the prototype.
import { TREND_MONTHS } from "./miraLandingMetrics";

export { TREND_MONTHS };

export const OUTCOME_KPIS = [
  {
    id: "conversion",
    label: "Sales Conversion",
    value: "24%",
    suffix: "%",
    change: { value: "+3 pts", dir: "up", good: true },
    trend: [18, 19, 20, 21, 22, 23, 22, 24],
    accent: "var(--chart-blue)",
  },
  {
    id: "retention",
    label: "Retention",
    value: "91%",
    suffix: "%",
    change: { value: "+1 pt", dir: "up", good: true },
    trend: [88, 88, 89, 90, 90, 91, 90, 91],
    accent: "var(--chart-teal)",
  },
  {
    id: "csat",
    label: "CSAT",
    value: "86%",
    suffix: "%",
    change: { value: "-2 pts", dir: "down", good: false },
    trend: [89, 90, 89, 88, 87, 88, 87, 86],
    accent: "var(--chart-green)",
  },
  {
    id: "winrate",
    label: "Win Rate",
    value: "31%",
    suffix: "%",
    change: { value: "+4 pts", dir: "up", good: true },
    trend: [25, 26, 27, 28, 29, 30, 29, 31],
    accent: "var(--chart-lavender)",
  },
  {
    id: "dealsize",
    label: "Avg Deal Size",
    value: "$12.4k",
    prefix: "$",
    suffix: "k",
    change: { value: "+6%", dir: "up", good: true },
    trend: [9.8, 10.1, 10.6, 11, 11.5, 11.8, 12, 12.4],
    accent: "var(--chart-amber)",
  },
  {
    id: "nps",
    label: "NPS",
    value: "42",
    suffix: "",
    change: { value: "+5", dir: "up", good: true },
    trend: [30, 32, 34, 36, 38, 40, 39, 42],
    accent: "var(--chart-sky)",
  },
  {
    id: "pipeline",
    label: "Pipeline Coverage",
    value: "3.1x",
    suffix: "x",
    change: { value: "-0.2x", dir: "down", good: false },
    trend: [3.4, 3.5, 3.3, 3.4, 3.2, 3.3, 3.2, 3.1],
    accent: "var(--chart-coral)",
  },
];

// AMP-authored stories living in the space — authored once, viewable by
// everyone (default-public), with pinned insights others can jump to.
export const SPACE_STORIES = [
  {
    id: "st-1",
    title: "Why did Sales Conversion climb in May?",
    date: "2 days ago",
    visibility: "public",
    pins: 3,
    kpiId: "conversion",
    tldr: "Conversion rose 3 pts to 24% in May — driven by faster follow-up on inbound demo requests and a tighter qualification step earlier in the funnel.",
  },
  {
    id: "st-2",
    title: "Retention risk concentrated in enterprise accounts",
    date: "4 days ago",
    visibility: "public",
    pins: 2,
    kpiId: "retention",
    tldr: "Retention holds at 91% overall, but enterprise renewals are softening — three accounts show declining usage and open escalations heading into renewal.",
  },
  {
    id: "st-3",
    title: "What's driving the CSAT dip on billing?",
    date: "1 week ago",
    visibility: "public",
    pins: 5,
    kpiId: "csat",
    tldr: "CSAT slipped 2 pts to 86%, concentrated in billing-related contacts where dispute handling runs slow and hand-offs repeat.",
  },
  {
    id: "st-4",
    title: "Win rate by competitor — Q2 readout",
    date: "1 week ago",
    visibility: "private",
    pins: 1,
    kpiId: "winrate",
    tldr: "Win rate climbed to 31% in Q2; we win against Competitor A on time-to-value but lose to Competitor B on price in mid-market deals.",
  },
  {
    id: "st-5",
    title: "Deal-size trends by customer segment",
    date: "2 weeks ago",
    visibility: "public",
    pins: 4,
    kpiId: "dealsize",
    tldr: "Average deal size grew 6% to $12.4k, led by mid-market multi-product deals; enterprise single-product deals are flat.",
  },
];

// Shared analytical body for a story's detail view. The narrative shape is
// the same across stories (the per-story tldr + KPI carry the specifics) —
// "author the story once" template from the ticket.
export const STORY_SECTIONS = [
  {
    heading: "What happened",
    body: "The metric moved outside its recent band this period. The shift is concentrated in a subset of segments rather than spread evenly, so the headline number understates how sharp the change is where it's happening.",
  },
  {
    heading: "Why it happened",
    body: "Two drivers explain most of the move: a process change that landed mid-period, and a shift in the mix of contacts. Sentiment and handle-time signals line up with the same segments, which rules out a one-off data artifact.",
  },
  {
    heading: "Recommended next step",
    body: "Focus on the one segment carrying most of the delta. A short, weekly review loop there will tell us within two weeks whether the change holds — before committing a broader playbook.",
  },
];

export const STORY_PINNED = [
  { text: "The top segment alone accounts for ~60% of the period-over-period move.", by: "Priya Nair" },
  { text: "Sentiment and handle time track the same accounts — this is a real shift, not a data blip.", by: "Marco Rossi" },
];

export const STORY_COMMENTS = [
  { user: "Sofia Almeida", initials: "SA", text: "Pulling logistics into this — the hand-off delay is on our side. Will add notes.", time: "1 day ago" },
  { user: "James Park", initials: "JP", text: "Pinned the segment chart. Can we get last quarter as a comparison?", time: "22 hours ago" },
];

export const STORY_COLLABORATORS = [
  { name: "Priya Nair", initials: "PN" },
  { name: "Marco Rossi", initials: "MR" },
  { name: "Sofia Almeida", initials: "SA" },
];

export function kpiSuggestions(label) {
  return [
    `What changed in ${label} this month?`,
    `Which segments drive ${label}?`,
    `Forecast ${label} for next quarter`,
  ];
}
