// Data for the "KPI Space" landing direction — the outcome-space surface from
// the [Ask Mira Pro] Landing page ticket (Jun 19 sharpening): pre-populated
// outcome KPIs, AMP-authored stories (generated by tasks, default-public),
// and the space's chats. Figures are illustrative for the prototype.
import { TREND_MONTHS } from "./miraLandingMetrics";

export { TREND_MONTHS };

export const OUTCOME_KPIS = [
  {
    id: "conversion",
    label: "Sales Conversion",
    value: "24%",
    suffix: "%",
    change: { value: "+3 pts", dir: "up", good: true },
    trend: [18, 19, 20, 21, 22, 23, 22, 24],
    accent: "var(--chart-blue)",
  },
  {
    id: "retention",
    label: "Retention",
    value: "91%",
    suffix: "%",
    change: { value: "+1 pt", dir: "up", good: true },
    trend: [88, 88, 89, 90, 90, 91, 90, 91],
    accent: "var(--chart-teal)",
  },
  {
    id: "csat",
    label: "CSAT",
    value: "86%",
    suffix: "%",
    change: { value: "-2 pts", dir: "down", good: false },
    trend: [89, 90, 89, 88, 87, 88, 87, 86],
    accent: "var(--chart-green)",
  },
  {
    id: "winrate",
    label: "Win Rate",
    value: "31%",
    suffix: "%",
    change: { value: "+4 pts", dir: "up", good: true },
    trend: [25, 26, 27, 28, 29, 30, 29, 31],
    accent: "var(--chart-lavender)",
  },
  {
    id: "dealsize",
    label: "Avg Deal Size",
    value: "$12.4k",
    prefix: "$",
    suffix: "k",
    change: { value: "+6%", dir: "up", good: true },
    trend: [9.8, 10.1, 10.6, 11, 11.5, 11.8, 12, 12.4],
    accent: "var(--chart-amber)",
  },
  {
    id: "nps",
    label: "NPS",
    value: "42",
    suffix: "",
    change: { value: "+5", dir: "up", good: true },
    trend: [30, 32, 34, 36, 38, 40, 39, 42],
    accent: "var(--chart-sky)",
  },
  {
    id: "pipeline",
    label: "Pipeline Coverage",
    value: "3.1x",
    suffix: "x",
    change: { value: "-0.2x", dir: "down", good: false },
    trend: [3.4, 3.5, 3.3, 3.4, 3.2, 3.3, 3.2, 3.1],
    accent: "var(--chart-coral)",
  },
];

// AMP-authored stories living in the space — authored once, viewable by
// everyone (default-public), with pinned insights others can jump to.
export const SPACE_STORIES = [
  { id: "st-1", title: "Why did Sales Conversion climb in May?", date: "2 days ago", visibility: "public", pins: 3 },
  { id: "st-2", title: "Retention risk concentrated in enterprise accounts", date: "4 days ago", visibility: "public", pins: 2 },
  { id: "st-3", title: "What's driving the CSAT dip on billing?", date: "1 week ago", visibility: "public", pins: 5 },
  { id: "st-4", title: "Win rate by competitor — Q2 readout", date: "1 week ago", visibility: "private", pins: 1 },
  { id: "st-5", title: "Deal-size trends by customer segment", date: "2 weeks ago", visibility: "public", pins: 4 },
];

export function kpiSuggestions(label) {
  return [
    `What changed in ${label} this month?`,
    `Which segments drive ${label}?`,
    `Forecast ${label} for next quarter`,
  ];
}
